openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/all_orders/:
    get:
      operationId: api_all_orders_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/all_tariffs/:
    get:
      operationId: api_all_tariffs_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/clients/{chat_id}:
    get:
      operationId: api_clients_retrieve
      parameters:
      - in: path
        name: chat_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/clients/{chat_id}/orders:
    get:
      operationId: api_clients_orders_retrieve
      parameters:
      - in: path
        name: chat_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/clients/add/:
    post:
      operationId: api_clients_add_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ClientRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ClientRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/freelancers/{chat_id}:
    get:
      operationId: api_freelancers_retrieve
      parameters:
      - in: path
        name: chat_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/freelancers/{chat_id}/orders:
    get:
      operationId: api_freelancers_orders_retrieve
      parameters:
      - in: path
        name: chat_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/freelancers/add:
    post:
      operationId: api_freelancers_add_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FreelancerRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FreelancerRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FreelancerRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/freelancers/appoint:
    post:
      operationId: api_freelancers_appoint_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderAppointFreelancerRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderAppointFreelancerRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderAppointFreelancerRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/order/{order_id}:
    get:
      operationId: api_order_retrieve
      parameters:
      - in: path
        name: order_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/order/add:
    post:
      operationId: api_order_add_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/order/find:
    get:
      operationId: api_order_find_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/tariff/{tariff_name}:
    get:
      operationId: api_tariff_retrieve
      parameters:
      - in: path
        name: tariff_name
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    ClientRequest:
      type: object
      properties:
        chat_id:
          type: integer
          title: ID чата в ТГ
        tariff:
          type: string
          minLength: 1
      required:
      - chat_id
      - tariff
    FreelancerRequest:
      type: object
      properties:
        chat_id:
          type: integer
          title: ID чата в ТГ
      required:
      - chat_id
    OrderAppointFreelancerRequest:
      type: object
      properties:
        chat_id:
          type: integer
        order_id:
          type: integer
      required:
      - chat_id
      - order_id
    OrderCreateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        chat_id:
          type: integer
      required:
      - chat_id
      - description
      - title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
